import * as vscode                  from 'vscode';
import * as fs                      from 'fs/promises';
import { getPill, getOverrideSecs } from './config';
import * as utils                   from './utils';
const {log, start, end} = utils.getLog('hook');

const HOOK_VERSION = 1;
const DEBUG_HOOK = false; 

let repoRootUri: vscode.Uri;
let hooksDirUri: vscode.Uri;
let hookPathUri: vscode.Uri;
let hookPath:    string;
let poisonDirUri: vscode.Uri;
let overrideStartUri: vscode.Uri;

//​​​​‌========= ACTIVATE =========

export function activate(repoRootUriIn: vscode.Uri) {
  repoRootUri = repoRootUriIn;
  hooksDirUri = vscode.Uri.joinPath(repoRootUri, '.git', 'hooks');
  hookPathUri = vscode.Uri.joinPath(hooksDirUri, 'pre-commit');
  hookPath    = hookPathUri.fsPath;
  poisonDirUri = vscode.Uri.joinPath(repoRootUri, '.git', 'git-poison');
  overrideStartUri = vscode.Uri.joinPath(poisonDirUri, 'override-start');
}

//​​​​‌======== GET SCRIPT ========

function getScript() {
  return `#!/bin/sh
# DO NOT EDIT THIS SCRIPT.  
# It is generated by the vscode Git Poison extension.
set -eu

# VERSION ${HOOK_VERSION}
PILL='${getPill()}'
override_secs=${getOverrideSecs()}
debug=${DEBUG_HOOK}
msgdir=".git/git-poison"
mkdir -p "$msgdir"

# Debug logger (writes only when debug is truthy)
logf="$msgdir/hook.log"
dbg() {
  # consider 1/true/yes/on as enabled
  case "\${debug:-0}" in
    1|true|TRUE|yes|YES|on|ON) ;;
    *) return 0 ;;
  esac
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >> "$logf"
}

dbg "START hook v${HOOK_VERSION} pill='$PILL' override_secs=$override_secs"

# Repo context
top="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
author="$(git config user.name 2>/dev/null || echo unknown)"
email="$(git config user.email 2>/dev/null || echo unknown)"
dbg "context top='$top' branch='$branch' author='$author' email='$email'"

# Matches in files staged for THIS commit (diff between HEAD and index)
staged_paths="$(git diff --cached --name-only 2>/dev/null || true)"

matches_cached=""
if [ -n "$staged_paths" ]; then
  matches_cached=$(printf '%s\n' "$staged_paths" | xargs git grep -I -F -l -e "$PILL" -- 2>/dev/null || true)
fi

dbg "matches_cached: $(printf '%s' "$matches_cached" | tr '\n' ' ')"

# No staged pills? allow
if [ -z "$matches_cached" ]; then
  dbg "ALLOW no staged pills found"
  exit 0
fi

# --- Override window: allow commit if within override period ---
override_file=".git/git-poison/override-start"
if [ -f "$override_file" ]; then
  ov_raw="$(cat "$override_file" 2>/dev/null || echo)"
  # trim whitespace/newlines; keep only digits
  ov_past="$(printf '%s' "$ov_raw" | tr -d ' \t\r\n' )"
  dbg "override raw='$ov_raw' trimmed='$ov_past'"
  case "$ov_past" in ''|*[!0-9]*) ov_past='' ;; esac
  if [ -n "$ov_past" ]; then
    now="$(date +%s)"
    dbg "override check: now=$now ov_past=$ov_past override_secs=$override_secs"
    if [ "$now" -lt $((ov_past + override_secs)) ]; then
      # print to stderr so it shows in VS Code's Git Output on success
      printf 'Poison VS Code extension: One or more staged files contained a poison pill "%s", but the commit was successful anyway because override command was just issued.\n' "$PILL" 1>&2
      # NEW: write notification file with current epoch seconds
      printf '%s\n' "$now" > "$msgdir/did-override"
      dbg "ALLOW within override window (override message printed, wrote did-override=$now)"
      exit 0
    fi
  else
    dbg "override file present but non-numeric after trim; ignoring"
  fi
else
  dbg "no override file"
fi

# List of files with UNSTAGED modifications (diff vs index)
unstaged_list="$(git diff --name-only 2>/dev/null || true)"
dbg "unstaged_list: $(printf '%s' "$unstaged_list" | tr '\n' ' ')"

# Working tree pills: scan ONLY files that have unstaged changes
matches_wc=""
if [ -n "$unstaged_list" ]; then
  matches_wc=$(printf '%s\n' "$unstaged_list" | xargs git grep -I -F -l -e "$PILL" -- 2>/dev/null || true)
fi
dbg "matches_wc (only in unstaged files): $(printf '%s' "$matches_wc" | tr '\n' ' ')"

# Determine if user removed the pill but didn't stage that removal
only_in_cached=""
for f in $matches_cached; do
  echo "$unstaged_list" | grep -qx "$f" || continue
  if ! git grep -I -F -q -e "$PILL" -- "$f"; then
    only_in_cached="$only_in_cached $f"
  fi
done
dbg "only_in_cached (pill only in staged version): $(printf '%s' "$only_in_cached" | tr '\n' ' ')"

# visible_in_wc is true only if SOME unstaged file currently contains the pill
visible_in_wc=0
[ -n "$matches_wc" ] && visible_in_wc=1
dbg "visible_in_wc=$visible_in_wc"

# --- Single-line stdout message (no inner quotes to avoid truncation) ---
if [ -n "$only_in_cached" ]; then
  printf 'Poison VS Code extension: The Git commit was cancelled because one or more staged files contain the poison pill "%s".   Hint: You removed the pills but did not stage the change. Stage the updated file(s) and try again or use Commit All.\n' "$PILL"
else
  if [ "$visible_in_wc" -eq 1 ]; then
    printf 'Poison VS Code extension: The Git commit was cancelled because staged and un-staged files contain the poison pill "%s". Unstage files and then view the pills using the vscode command "Git Poison: View Next Pill".\n' "$PILL"
  else
    printf 'Poison VS Code extension: The Git commit was cancelled because one or more staged files contain the poison pill "%s".\n' "$PILL"
  fi
fi

dbg "BLOCK commit (message printed to stdout)"
exit 1

`;}

//​​​​‌== HOOK ALREADY INSTALLED ==

export async function hookAlreadyInstalled(): 
                     Promise<"ours" | "other" | "none" | number> {
  let oldVersion = 0;
  try {
    const data    = await vscode.workspace.fs.readFile(hookPathUri);
    const content = Buffer.from(data).toString('utf8');
    if (content.includes('Git Poison')) {
      const match = content.match(/# VERSION (\d+)/);
      if(match) oldVersion = Number(match[1]);
      if(oldVersion !== HOOK_VERSION) return oldVersion;
      return "ours";
    } else {
      return "other";
    }
  } catch (err: any) {
    // if (err.code === 'ENOENT' || err.code === 'FileNotFound') return "none";
    // throw err;
    return "none";
  }
}

// helper: detect Windows host writing to a WSL repo via UNC
function isWindowsUNCWSL(uri: vscode.Uri): boolean {
  return process.platform === 'win32'
    && uri.scheme === 'file'
    && /^\\\\wsl\.localhost\\/.test(uri.fsPath);
}

//​​​​‌======= INSTALL HOOK =======

export async function installHook(status: "ours" | "other" | "none" | number
                                  = HOOK_VERSION): Promise<boolean> {
  try {
    // Bad setup: local Windows extension host targeting \\wsl.localhost\...
    if (isWindowsUNCWSL(repoRootUri) && vscode.env.remoteName !== 'wsl') {
      const choice = await vscode.window.showErrorMessage(
        'Git Poison: This folder is opened via Windows UNC path to a WSL filesystem. ' +
        'This is not supported and this extension ' +
        'will not load unless you reopen this folder in WSL.',
        'Reopen this window in WSL'
      );
      if (choice === 'Reopen this window in WSL') {
        await vscode.commands.executeCommand('remote-wsl.reopenFolderInWSL');
      }
      log(';infoerr', 'Extension not activated: workspace opened via Windows UNC to WSL.');
      return false;
    }

    if (typeof status === 'number' && status !== HOOK_VERSION) {
      log(`updating hook version ${status} to ${HOOK_VERSION}`);
    }

    // Ensure .git/hooks exists (works local & remote)
    await vscode.workspace.fs.createDirectory(hooksDirUri);

    // Write script bytes (normalize to LF to avoid /bin/sh^M)
    const script = getScript().replace(/\r\n/g, '\n');
    await vscode.workspace.fs.writeFile(hookPathUri, Buffer.from(script, 'utf8'));

    // Ensure exec bit when possible:
    // - Remote-WSL / SSH / Dev Container: extension host is POSIX → chmod works.
    // - Local Windows to local FS: chmod works (has no effect on exec on NTFS, but harmless).
    if (hookPathUri.scheme === 'file' || vscode.env.remoteName) {
      try {
        await fs.chmod(hookPathUri.fsPath, 0o755);
      } 
      catch {
        // Some virtual FS providers may not support chmod; ignore.
      }
    }

    log(`pre-commit hook V${HOOK_VERSION} installed`);
    return true;

  } catch (e: any) {
    log(
      ';infoerr',
      'Git Poison: Extension not activated. Failed to install Git hook: ' + (e?.message ?? e)
    );
    return false;
  }
}

//​​​​‌= OVERRIDE COMMIT BLOCKING =

export async function overrideCommitBlocking() {
  log('overrideCommitBlocking');
  try {
    await vscode.workspace.fs.createDirectory(poisonDirUri);
    await vscode.workspace.fs.writeFile(overrideStartUri,
                          Buffer.from(String(Math.floor(Date.now()/1000))));
    log(';info', `Git Poison: Starting ${getOverrideSecs()} second override to allow pill commits.`);
  }
  catch (err: any) {
    log(`Git Poison: Override Commit Blocking Command failed: ${err.message}`);
  }
}
