import * as fs     from 'fs/promises';
import * as path   from 'path';
import * as utils  from './utils';
const {log, start, end} = utils.getLog('hook');

const HOOK_VERSION = 2;
const pillStr = '//❌';

const script = 

`#!/bin/sh
# DO NOT EDIT THIS SCRIPT.  
# It is generated by the vscode Git Poison extension.
set -eu

# VERSION ${HOOK_VERSION}
PILL='${pillStr}'
msgdir=".git/git-poison"
mkdir -p "$msgdir"

# Repo context
top="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
author="$(git config user.name 2>/dev/null || echo unknown)"
email="$(git config user.email 2>/dev/null || echo unknown)"

# Matches in the STAGED index (what will be committed)
matches_cached=$(git grep -I --cached -l -e "$PILL" -- . || true)

# No staged pills? allow
[ -z "$matches_cached" ] && exit 0

# Also check WORKING TREE (what's in the editor)
matches_wc=$(git grep -I -l -e "$PILL" -- . || true)

# Determine if user removed the pill but didn't stage that removal
only_in_cached=""
for f in $matches_cached; do
  echo "$matches_wc" | grep -qx "$f" || only_in_cached="$only_in_cached $f"
done

# --- Single-line stdout message (avoid inner quotes to prevent truncation) ---
if [ -n "$only_in_cached" ]; then
  # Pills exist only in staged version, not working copy
  printf 'Poison vscode extension: The Git commit was cancelled because one or more staged files contain a poison pill "%s".   Hint: You removed the pill but did not stage the change. Stage the updated file(s) or use Commit All and try again.\n' "$PILL"
else
  # Pills are also visible in the working copy
  printf 'Poison vscode extension: The Git commit was cancelled because one or more files contain the poison pill "%s". You can view the pills using the vscode command \"Git Poison: View Next Pill\".\n' "$PILL"
fi

exit 1
`;

export async function hookAlreadyInstalled(repoRoot: string): 
                     Promise<"ours" | "other" | "none" | number> {
  let oldVersion = 0;
  const hookPath = path.join(repoRoot, '.git', 'hooks', 'pre-commit');
  try {
    const content = await fs.readFile(hookPath, 'utf8');
    if (content.includes('Git Poison')) {
      const match = content.match(/# VERSION (\d+)/);
      if(match) oldVersion = Number(match[1]);
      if(oldVersion !== HOOK_VERSION) return oldVersion;
      return "ours";
    } else {
      return "other";
    }
  } catch (err: any) {
    if (err.code === 'ENOENT') return "none";
    throw err;
  }
}

export async function installHook(repoRoot: string, 
             status: "ours" | "other" | "none" | number): Promise<boolean> {
  try {
    if(typeof status === "number")
      log(`updating hook version ${status} to ${HOOK_VERSION}`);
    const hooksDir = path.join(repoRoot, '.git', 'hooks');
    await fs.mkdir(hooksDir, { recursive: true });
    const hookPath = path.join(hooksDir, 'pre-commit');
    await fs.writeFile(hookPath, script.replace(/\r\n/g, '\n'), { mode: 0o755 });
    if (process.platform !== 'win32') await fs.chmod(hookPath, 0o755);
    log('pre-commit hook installed');
  } catch (e: any) {
    log('infoerr', 'Git Poison: Extension not activated. ' +
                   'Failed to install Git hook: ' + (e?.message ?? e));
    return false;
  }
  return true;
}
